---
- name: Build yay
  shell: type yay
  register: command_result
  failed_when: command_result.rc > 1

- when: command_result.rc != 0
  block:
    - name: Download yay from github
      git:
        repo: 'https://aur.archlinux.org/yay.git'
        dest: "{{ destdir }}"

    - name: Build yay
      command: makepkg -s
      args:
        chdir: "{{ destdir }}"
        creates: 'yay'

    - name: Find yay build to install
      find:
        paths: "{{ destdir }}"
        patterns: "yay-*.pkg.tar.xz"
      register: to_install

    - name: Install yay from file
      become: true
      pacman:
        name: "{{ to_install.files[0].path }}"
        state: latest

  always:
    - name: Cleanup yay build dir
      file:
        path: "{{ destdir }}"
        state: absent
