---
- name: Download yay from github
  become_user: y9mo
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: "{{ destdir }}"

- name: Build yay
  shell:
    "makepkg -s"
  args:
    chdir: "{{ destdir }}"

- name: Ansible delete file wildcard
  find:
    paths: "{{ destdir }}"
    patterns: "yay-*.pkg.tar.xz"
  register: to_install

- name: Workaround to install package from file
  become: true
  pacman:
    name: "{{ to_install.files[0].path }}"
    state: latest
