---
- hosts: localhost
  name: Configure xps workstation
  become: yes
  vars:
    user:
      name: y9mo
      shell: /usr/bin/zsh

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Enable wheel group as sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) ALL'
        validate: 'visudo -cf %s'

    - name: Create {{ user.name }} user
      user:
        name: "{{ user.name }}"
        password: '$6$l5arRlpsqjrMf$5RVJYtvhga9O75kTFgioLCPVGBFyQX54Yg.V9R.MtCIAg51.rlS7h6v2dK/PRYgQZkaWA/dwq7IrqGnT6Q2jA1'
        groups: wheel,video
        state: present
        shell: "{{ user.shell }}"

    - name: Create file to disable sudo lecture
      file:
        path: "/var/db/sudo/lectured/{{ user.name }}"
        state: touch
        mode: u=rw,g=,o=
        group: "{{ user.name }}"
        modification_time: preserve
        access_time: preserve

    - name: Download ansible repo from github
      git:
        repo: https://github.com/y9mo/xt5f0b.git
        dest: "/home/{{ user.name }}/.xt5f0b"

    - name: Create empty .zshrc
      file:
        path: "/home/{{ user.name }}/.zshrc"
        state: touch
        mode: u=rw,g=r,o=r
        modification_time: preserve
        access_time: preserve
        owner: "{{ user.name }}"
        group: "{{ user.name }}"

    - name: Recursively change ownership of ansible repo
      file:
        path: "/home/{{ user.name }}/.xt5f0b"
        state: directory
        recurse: yes
        owner: "{{ user.name }}"
        group: "{{ user.name }}"

    - name: Install go
      pacman:
        name:
          - go
        state: present

    - name: Build yay
      shell: type yay
      register: command_result
      failed_when: command_result.rc > 1

    - when: command_result.rc != 0
      block:
        - name: Download yay from github
          git:
            repo: 'https://aur.archlinux.org/yay.git'
            dest: "{{ destdir }}"
          become: yes
          become_user: y9mo

        - name: Build yay
          command: makepkg -s
          args:
            chdir: "{{ destdir }}"
            creates: 'yay'
          become: yes
          become_user: y9mo

        - name: Find yay build to install
          find:
            paths: "{{ destdir }}"
            patterns: "yay-*.pkg.tar.xz"
          register: to_install

        - name: Install yay from file
          become: true
          pacman:
            name: "{{ to_install.files[0].path }}"
            state: latest

      always:
        - name: Cleanup yay build dir
          file:
            path: "{{ destdir }}"
            state: absent

    - name: Build and Install new protocol library and tools to communicate with iOS®
      aur:
        use: yay
        name:
          - libimobiledevice-git
        skip_installed: yes
      become: yes
      become_user: y9mo
