---
  - name: Install Xorg base
    become: true
    pacman:
      name:
      - xorg-server
      - xorg-xinit
      - xorg-xrdb

  - name: Install other
    become: true
    pacman:
      name:
      - xf86-video-intel
      - xf86-input-libinput
