---
  - name: Install Xorg base
    become: true
    pacman:
      name:
      - xorg-server
      - xorg-xinit
      - xorg-xrdb
      - xterm
      state: present

  - name: Install xdg-user-dirs tool
    become: true
    pacman:
      name:
        - xdg-user-dirs
      state: present

  - name: Creating user's default directories
    shell: xdg-user-dirs-update
