#- name: Install dep
#  pacman:
#    name:
#      - git
#      - go
#      - sudo
#      - zsh
#      - yarn
#    state: present

- name: Clone dotfiles from GitHub
  git:
    repo: "{{ user.dotfiles }}"
    dest: "/home/{{ user.name }}/.config"
    force: yes

- name: clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ user.name }}/.oh-my-zsh"

- name: Create symlink to zshrc
  file:
    src: "/home/{{ user.name }}/.config/shell/.zshrc"
    dest: "/home/{{ user.name }}/.zshrc"
    state: link
    force: yes
    follow: false
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Create nvim autoload and plugged in config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: [
    "/home/{{ user.name }}/.config/nvim/autoload",
    "/home/{{ user.name }}/.config/nvim/plugged"
  ]

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user.name }}/.config/nvim/autoload/plug.vim"
    force: yes

- name: Install vim plugins
  command: nvim --headless +PluginInstall +qa
