#- name: Install dep
#  pacman:
#    name:
#      - git
#      - go
#      - neovim
#      - sudo
#      - zsh
#      - yarn
#    state: present

- name: Clone dotfiles from GitHub
  git:
    repo: "{{ user.dotfiles }}"
    dest: "/home/{{ user.name }}/.config"
    force: yes

- name: clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ user.name }}/.oh-my-zsh"

- name: Create symlink to zshrc
  file:
    src: "/home/{{ user.name }}/.config/shell/.zshrc"
    dest: "/home/{{ user.name }}/.zshrc"
    state: link
    force: yes
    follow: false
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Create symlink to tmux conf
  file:
    src: "/home/{{ user.name }}/.config/tmux/tmux.conf"
    dest: "/home/{{ user.name }}/.tmux.conf"
    state: link
    force: yes
    follow: false
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Create nvim autoload and plugged in config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: [
    "/home/{{ user.name }}/.config/nvim/autoload",
    "/home/{{ user.name }}/.config/nvim/plugged"
  ]

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user.name }}/.config/nvim/autoload/plug.vim"
    force: yes

- name: Check if plugin folder is empty before proceeding
  find:
    paths: "/home/{{ user.name }}/.config/nvim/plugged"
  register: plugin_not_found

- when: plugin_not_found
  block:
   - name: Install vim plugins
     command: nvim --headless +PlugInstall +qa

- name: Install TPM for tmux
  shell: type tmux
  register: command_result
  failed_when: command_result.rc > 1

- when: command_result.rc != 0
  block:
    - name: Create tmux plugins directory
      file:
        path: "/home/{{ user.name }}/.config/tmux/plugins"
        state: directory
        mode: '0755'

    - name: Clone Tmux Plugin Manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "/home/{{ user.name }}/.config/tmux/plugins/tpm"

    - name: Install Tmux plugins
      command: "/home/{{ user.name }}/.config/tmux/plugins/tpm/bin/install_plugins"
