---
- name: Install Xorg base
  become: true
  pacman:
    name:
    - xorg-server
    - xorg-xinit
    - xorg-xrandr
    - xorg-xrdb
    state: present

- name: Install xdg-user-dirs tool
  become: true
  pacman:
    name:
      - xdg-user-dirs
    state: present

- name: Check user default dir exists
  stat:
    path: '/home/{{ user.name }}/Downloads'
  changed_when: false
  register: downloads_home

- when: not downloads_home.stat.exists
  block:
    - name: Creating user's default directories
      command: xdg-user-dirs-update

- name: Install i3wm and desktop like stuffs
  become: true
  pacman:
    name:
      - bind-tools
      - dunst
      - feh
      - i3-wm
      - i3lock
      - i3status
      - rofi
    state: present

- name: Install fonts with yay
  aur:
    use: yay
    name:
      - nerd-fonts-inconsolata
      - nerd-fonts-noto
      - nerd-fonts-source-code-pro
      - tamzen-font-git
      - nerd-fonts-iosevka
      - ttf-unifont
    skip_installed: yes

- name: Create polybar/i3 config directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: [
    "/home/{{ user.name }}/.config/i3"
  ]

- name: Install SDDM
  become: true
  pacman:
    name:
      - sddm
      - qt5-svg
    state: present

- name: Install SDDM Theme
  aur:
    use: yay
    name:
      - chili-sddm-theme
    skip_installed: yes

- name: Specify SDDM greeter theme
  become: true
  lineinfile:
    path: /etc/sddm.conf.d/sddm.conf
    regexp: "^Current="
    line: "[Theme]\nCurrent=chili"
    state: present
    create: yes

- name: Set user profile pic
  become: true
  copy:
    src: icon/mask.png
    dest: /usr/share/sddm/faces/{{ user.name }}.face.icon

- name: Copy background
  copy:
    src: backgrounds
    dest: /home/{{ user.name }}/Pictures

- name: Enable SDDM
  become: true
  service:
    name: sddm.service
    enabled: yes

- name: Install firefox chromium hunspell
  become: true
  pacman:
    name:
      - firefox-developer-edition
      - chromium
      - hunspell
      - hunspell-en_US
      - hunspell-fr
    state: present
