---
- name: Install SDDM
  become: true
  pacman:
    name:
      - sddm
      - qt5-svg
    state: present

- name: Install SDDM Theme
  aur:
    use: yay
    name:
      - chili-sddm-theme
    skip_installed: yes

- name: Specify SDDM greeter theme
  become: true
  lineinfile:
    path: /etc/sddm.conf.d/sddm.conf
    regexp: "^Current="
    line: "[Theme]\nCurrent=chili"
    state: present
    create: yes

- name: Set user profile pic
  become: true
  copy:
    src: icon/mask.png
    dest: /usr/share/sddm/faces/{{ user.name }}.face.icon

- name: Copy background
  copy:
    src: backgrounds
    dest: /home/{{ user.name }}/Pictures

- name: Enable SDDM
  become: true
  service:
    name: sddm.service
    enabled: yes
