---
- name: Install i3
  become: true
  pacman:
    name:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
    state: present

- name: Install py3status
  become: true
  pacman: name=py3status state=present
