---
- name: Install i3
  become: true
  pacman:
    name:
      - i3-wm
      - i3lock
      - dmenu
    state: present

- name: Set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"

- name: Install polybar
  aur:
    use: yay
    name:
      - polybar
      - ttf-unifont
    skip_installed: yes

- name: Create polybar/i3 config directory if it does not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items: [
    "/home/{{ user.name }}/.config/i3",
    "/home/{{ user.name }}/.config/polybar"
  ]

- name: Copy polybar config file with owner and permissions
  copy:
    src: /usr/share/doc/polybar/config
    dest: "/home/{{ user.name }}/.config/polybar/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Copy i3 launch file with owner and permissions
  copy:
    src: launch.sh
    dest: "/home/{{ user.name }}/.config/polybar/launch.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'

- name: Copy i3 config file with owner and permissions
  copy:
    src: /etc/i3/config
    dest: "/home/{{ user.name }}/.config/i3/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Add polybar exec line at end of i3 config file
  lineinfile:
    path: "/home/{{ user.name }}/.config/i3/config"
    line: "exec_always --no-startup-id /home/{{ user.name }}/.config/polybar/launch.sh"
    state: present
    insertafter: EOF
