---
- name: Install i3
  become: true
  pacman:
    name:
      - i3-wm
      - i3lock
      - dmenu
    state: present

- name: Set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"

- name: Install polybar
  aur:
    use: yay
    name:
      - polybar
      - ttf-unifont
    skip_installed: yes

- name: Create a polybar config directory if it does not exist
  file:
    path: "/home/{{ user.name }}/.config/polybar"
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  copy:
    src: /usr/share/doc/polybar/config
    dest: "/home/{{ user.name }}/.config/polybar/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Copy file with owner and permissions
  copy:
    src: launch.sh
    dest: "/home/{{ user.name }}/.config/polybar/launch.sh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
