---
- name: Install LightDM
  become: true
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present

- name: Enable LightDM
  become: true
  service: name=lightdm.service enabled=yes

- name: Set up greeter
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    state: present
    regexp: '^#greeter-session='
    line: 'greeter-session=lightdm-gtk-greeter'
