---
- name: Install universal base packages
  become: true
  pacman:
    name:
      - bc
      - evince
      - git
      - htop
      - jq
      - man-db
      - man-pages
      - ranger
    state: present
