---
- name: Install universal base packages
  become: true
  pacman:
    name:
      - aws-cli
      - bc
      - evince
      - git
      - htop
      - jq
      - man-db
      - man-pages
      - ranger
      - ripgrep
      - ruby
    state: present
