---
- name: Install awscli bat docker fd fzf go nodejs npm packer rg ruby yarn terraform
  become: true
  pacman:
    name:
      - alacritty
      - aws-cli
      - bat
      - docker
      - fd
      - fzf
      - go
      - nodejs
      - npm
      - packer
      - ripgrep
      - ruby
      - yarn
      - terraform
      - tmux
    state: present

- name: Check rust for existing install
  stat:
    path: '/home/{{ user.name }}/.rustup'
  changed_when: false
  register: rustup_home

- when: not rustup_home.stat.exists
  block:
    - name: Download https://sh.rustup.rs
      become: true
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: 755

    - name: Install rust with rustup
      become: true
      command: /tmp/rustup.sh -y
      args:
        creates: '/home/{{ user.name }}/.rustup'
  always:
    - name: Cleanup rustup
      become: true
      file:
        path: /tmp/rustup.sh
        state: absent

- name: Enable and start docker service
  become: true
  systemd:
    name: docker.service
    enabled: True
    state: started

- name: Make sure we have a 'docker' group
  become: true
  group:
    name: docker
    state: present

- name: Add user '{{ user.name }}' to 'docker' group
  become: true
  user:
    name: '{{ user.name }}'
    groups: docker
    append: 'yes'
