---
- name: Install golang
  become: true
  pacman:
    name: go

- name: Install rust by rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Install docker
  become: true
  pacman:
    name: docker
    state: present

- name: Enable and start docker service
  become: true
  systemd:
    name: docker.service
    enabled: True
    state: started

- name: Make sure we have a 'docker' group
  become: true
  group:
    name: docker
    state: present

- name: Add user '{{ user.name }}' to 'docker' group
  become: true
  user:
    name: '{{ user.name }}'
    groups: docker
    append: 'yes'
