---
- name: Install fonts
  become: true
  pacman:
    name:
      - noto-fonts
      - noto-fonts-emoji
      - terminus-font
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-freefont
      - ttf-hack
      - ttf-inconsolata
      - ttf-liberation
      - ttf-roboto
      - ttf-roboto-mono
      - ttf-ubuntu-font-family
    state: present
